# User config
author: "Li Yuchen  ╮(๑•́ ₃•̀๑)╭"
tagline: " Welcome ~~~ "
description: "Masters in Artificial Intelligence with a focus on data, cloud services, artificial intelligence, and software development."
# keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "yuchener.li@outlook.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed